#!/usr/bin/tcsh -f

setenv fifo_training `pwd`

if ( ! ${?labs_home} ) then
    setenv labs_home $fifo_training
endif

if ( ! ${?scripts} ) then
    setenv scripts $fifo_training/scripts
endif

echo labs_home = $labs_home
echo fifo_training = $fifo_training
echo scripts = $scripts
